### ISSUE TITLE
Register new Bot

### ISSUE THREAD

**Issue by denolia** [piterpy/confobo#1]
title: Confobo
username: `@confobot` or `@confo_bot`
title: test Confobo
username: `@testconfobot`

**Comment by lig** [comment]
Underscore looks like overkill for me. I'd prefer `confobot`

**Comment by denolia** [comment]
Of course, I just suggest other possible names if it is already occupied.

**Comment by denolia** [comment]
already taken(

**Comment by denolia** [comment]
testing bot username `@confobotestbot`
release bot username `@piterpybot`
